version: '3.1'
services:
  itoken-zipkin:
    restart: always
    image: jzh/itoken-zipkin
    container_name: itoken-zipkin
    ports:
      - 9411:9411
    networks:
      - itoken-zipkin

networks:
  itoken-zipkin: