spring:
  application:
    name: itoken-zuul
server:
  port: 8769

eureka:
  instance:
    hostname: 192.168.56.102
    instance-id: 192.168.56.102:8769

zuul:
  routes:
    backend-admin:
      path: /backend/admin/**
      serviceId: ${itoken.web.admin}
#      serviceId: itoken-web-admin
    backend-posts:
      path: /backend/posts/**
      serviceId: ${itoken.web.posts}
#      serviceId: itoken-web-posts