spring:
  application:
    name: itoken-eureka
#  boot:
#    admin:
#      client:
#        instance:
#          service-url: http://192.168.56.102:8761

server:
  port: 8761

eureka:
  client:
    # 表示是否将自己注册到 Eureka，因为要构建集群环境，需要将自己注册到集群，所以应该开启
    registerWithEureka: true
    # 表示是否从 Eureka 获取注册信息，如果是单一节点，不需要同步其它 Eureka 节点，则可以设置为 false，但此处为集群，应该设置为true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://192.168.56.102:8761/eureka/,http://192.168.56.102:8861/eureka/,http://192.168.56.102:8961/eureka/
  instance:
    prefer-ip-address: true
#    instance-id: 192.168.56.102:8761