version: '3.1'
services:
  itoken-zuul:
    restart: always
    image: jzh/itoken-zuul
    container_name: itoken-zuul
    ports:
      - 8769:8769
    networks:
      - itoken-zuul

networks:
  itoken-zuul: